name: 'Test'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, release/* ]
  release:
    types: [ published ]

jobs:
  job_win_build:
    name: 'Windows build'
    runs-on: windows-latest
    # Use PAT on Windows instead of SSH
    steps:  
    - uses: actions/checkout@v2
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: ${{ github.workspace }}\artifacts
        
    - name: echo
      run: echo ECHO!!!
    - name: 'configure for release'
      if: ${{github.event_name == 'release'}}
      run: echo RELEASE!!!
    - name: Get release
      if: ${{github.event_name == 'release'}}
      id: get_release
      uses: bruceadams/get-release@v1.2.2
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: 'attach artifacts to release page'  
      if: ${{github.event_name == 'release'}}
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./my-artifact.zip
        asset_name: my-artifact.zip
        asset_content_type: application/zip