name: 'Test'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, release/* ]
  release:
    types: [ published ]

jobs:
  job_win_build:
    name: 'Windows build'
    runs-on: windows-latest
    # Use PAT on Windows instead of SSH
    steps:  
    - uses: actions/checkout@v2
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: ${{ github.workspace }}\artifacts
        
    - name: echo
      run: echo ECHO!!!
    - name: 'configure for release'
      if: ${{github.event_name == 'release'}}
      run: echo RELEASE!!!
    - name: 'attach artifacts to release page'
      if: ${{github.event_name == 'release'}}
    - uses: Roang-zero1/github-upload-release-artifacts-action@master
        with:
            args:
            - my-artifact
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}