name: 'Test'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, release/* ]
  release:
    types: [ published ]

jobs:
  job_win_build:
    name: 'Windows build'
    runs-on: windows-latest
    # Use PAT on Windows instead of SSH
    steps:  
    - name: echo
      run: echo "ECHO!!!"
    - name: 'configure for release'
      if: ${{github.event_name == 'release'}}
      run: echo "RELEASE!!!"
    - name: 'Upload artifacts'
      uses: actions/upload-artifact@v2
      with:
        name: 'artifact_${{github.run_number}}'
        path: ${{ github.workspace }}\README.md